### PR TITLE
Request argument hash

### PR DESCRIPTION
**Pull request by RainerAtSpirit**
This fixes the issue discussed in https://www.flexmonster.com/question/flexmonster-mongo-connector-getdatafromcache-issue/

### CODE REVIEW

**Review by Uaman — COMMENTED** [review]
Thank you for your pull request.
We are going to review and merge it shortly.
The update is going to be released during the next connector minor release.

**Comment by Uaman** [comment]
We have reviewed the initial version of the pull request.
Some of the unnecessary dependencies were removed.
MongoDB driver was updated to v4.
The final version is already available in the master branch.
You are welcome to check it.

**Comment by RainerAtSpirit** [comment]
I can understand that you'd like to minimize dependencies on external libraries. However, `node-object-hash` supports the ordering of object props and arrays. That created the same hash values for `clientQueries` that only differ in order. 
That part is missing in  https://github.com/flexmonster/flexmonster-mongodb-connector/blob/aa675fc51ec6867e1a0e807e2e817857a52886e4/src/utils/HashGenerator.ts#L10

```
export interface CacheKeyInterface {
    clientQuery: string, // in other places that's an any
    databaseName: string,
    index: string    
}
```

**Comment by Uaman** [comment]
Thank you for noticing that clientQuery is not a string. Mostly, it is a JSON object.
Now, the same order is guaranteed internally:
https://github.com/flexmonster/flexmonster-mongodb-connector/blob/bff6f89cf13e22e28f955da382612c305857e055/src/cache/impl/LocalDataCache.ts#L147
In such a case, we will have different strings and different hashes for them.

**Comment by RainerAtSpirit** [comment]
You're right `clientQuery` is a JSON object of "unknown" format mostly an object. Neither props nor arrays of that object are sorted at the moment. 

```
JSON.stringify({a: 1, b: 2}) !== JSON.stringify({b: 2, a: 1}) //true
```

The initial approach using `node-object-hash` would have sorted those. That way the same hash value was produced because those are semantically the same.

**Comment by Uaman** [comment]
Thank you for writing.
Your arguments about the object's key order sound reasonable. Still, we strongly rely on Flexmonster client-side component algorithm for generating data queries. Therefore, the data query object's key order is expected to be consistent.

Also, there are some amount of cases related to the array order that cannot be granted by `node-object-hash`. For example, different order of `reportFilters` objects will lead to different hashes but the final MongoDB response will be the same.

If your use case requires such a strict level of hashing, we recommend overriding `getCacheKey` method outside of the module. https://github.com/flexmonster/flexmonster-mongodb-connector/blob/bff6f89cf13e22e28f955da382612c305857e055/src/cache/impl/LocalDataCache.ts#L145

**Comment by RainerAtSpirit** [comment]
@Uaman Sure, that will do.

**Pull request merged**
